name: 编译linux程序
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'gobang.py'
          requirements: "requirements.txt"
          upload_exe_with_name: 'gobang'
          options: --onefile, --name "gobang", -w, -i "gobang.ico", --add-data "data/gobang.png:data", --add-data "data/bgm.mp3:data", --add-data "data/simhei.ttf:data"